---
#
# Push to registry
#
- name: Push the final image with the proper COMMIT HASH to Docker Registry
  docker_image:
    name: "{{ image_name }}:{{ code_commit_hash.stdout }}"
    repository: "{{ docker_registry }}/{{ image_name }}:{{ code_commit_hash.stdout }}"
    push: true
  when: !custom_tag

- block:
  - name: Remove the remote {{ custom_tag }} tag incase we already have it
    docker_image:
      name: "{{ docker_registry }}/{{ image_name }}:{{ custom_tag }}"
      state: absent

  - name: Push the final image with the tag {{ custom_tag }}
    docker_image:
      name: "{{ image_name }}:{{ code_commit_hash.stdout }}"
      repository: "{{ docker_registry }}/{{ image_name }}:{{ custom_tag }}"
      push: true
  when: custom_tag

- block:
  - name: Remove the remote "latest" tag so we can tag as latest and push
    docker_image:
      name: "{{ docker_registry }}/{{ image_name }}:latest"
      state: absent

  - name: Push the final image with the tag "latest"
    docker_image:
      name: "{{ image_name }}:{{ code_commit_hash.stdout }}"
      repository: "{{ docker_registry }}/{{ image_name }}:latest"
      push: true
  when: push_as_latest

